src/view/lesson_environment.js
Messages were accumulating over multiple runs.
=> Clear execution-related messages on new execution.

src/lesson/lesson01.js, src/util/animator.js
Add the possibility of displacing the origin in the animator,
so that we can more easily centralize smaller grids.
Also, in lesson 1, calculate the optimal grid cell size instead of
using a constant (which didn't suit larger levels).
Fixes #12.
=> Support arbitrary grid sizes.

src/lesson/lesson01.js
It is now possible to create lessons with multiple simultaneous puzzles.
The lessons steps 11-14, as described in the Lesson 01 documentation, are now implemented.
=> Add Lesson01ExerciseStepPlayerMulti and lesson steps with 2 simultaneous puzzles

src/lesson/lesson02.js
Can be viewed in gpoesia.com/tests/lessons/lesson02.html
=> Add lesson 2 exercises.

src/language/interpreter.js, src/language/robolang/lexer.js, src/language/robolang/parser.js, src/language/robolang/robolang.js, src/language/robolang/test/test_robolang.js, src/test/run_tests.js
Robolang now supports variables in nested scopes and conditional
statements. For now, only one scope is created per program: the global
scope. Sensors are supposed to be global variables set by the lesson
engine after each player action.
=> Add variables and conditional statements to Robolang

src/language/interpreter.js, src/language/robolang/lexer.js, src/language/robolang/parser.js, src/language/robolang/robolang.js, src/language/robolang/test/test_robolang.js, src/language/scope.js, src/test/run_tests.js
Was missing in the related PR.
=> Add Scope implementation

src/view/lesson_environment.js
Tested on lesson 03, now the code does not reset when the user modifies their code. Also tested that rendering was still fine when advancing to the next level.
=> Do not reset when the code is modified (#44)

src/lesson/lesson03.js
These are positions the game camera cannot see.
=> Lesson 3: Add support for hidden (black) squares.

src/view/lesson_environment.js
This can be helpful in case of errors discovered during class.
To use it, click the code editor and press "Ctrl" + ";" (typing ";" may require holding Shift depending on your keyboard).
=> Add hotkeys for rapidly advancing a level.

src/constants.js, src/language/robolang/analysis.js, src/language/robolang/parser.js, src/language/robolang/robolang.js, src/language/robolang/test/test_analysis.js, src/lesson/lesson03.js
Adds a new parameter to Lesson03StepPlayer: require_conditionals. If true, the code only compiles if it has conditional statements (at least one).
Also, added a very basic static analysis framework for implementing the analysis of checking whether the code has conditionals in a more elegant manner.
=> Add possibility to require use of conditionals in lesson 3 steps

src/language/robolang/lexer.js, src/language/robolang/parser.js, src/language/robolang/robolang.js, src/language/robolang/test/test_robolang.js
Add optional 'else' to conditionals in robolang.
The syntax is: 
<sensor> ? {<then-code>} : {<else-code>}
=> Support optional 'else' in conditionals

package.json, src/view/code_editor.js
Update the CodeEditor module to use our external CodeEditor (published at https://www.npmjs.com/package/codeeditor)
This adds syntax highlighting, automatic indenting, and automatic closing blocks.
=> Update CodeEditor to use our external module.

src/view/lesson_environment.js, src/view/message_pane.js
Steps to verify the fix:
* Open any lesson
* Type some code that does not compile (e.g. `2{`)
* Click 'Play' multiple times
* Apply the PR
* Repeat
=> Fix compilation errors not being cleared properly (#56).

src/util/animator.js, src/view/lesson_environment.js
=> Fix behaviour on alternating 'play' and 'advance' buttons (#45, #60).

src/language/robolang/lexer.js, src/language/robolang/parser.js, src/language/robolang/test/test_analysis.js, src/language/robolang/test/test_robolang.js, src/view/code_editor.js
New if statement: se sensor { }
New if-else statement: se sensor { } senao { }
New while statement: enquanto sensor { }
This breaks the code size limits in lesson 3. This will be fixed in
another PR.
=> Change language syntax to be more explicit.

src/view/code_editor.js, src/view/lesson_environment.js
=> Make code editor always focused

src/constants.js, src/lesson/lesson01.js, src/lesson/lesson02.js, src/lesson/lesson03.js
=> Translate lesson{01,02} actions and descriptions

build.sh, package.json, src/app.js, src/constants.js, src/game/asteroids.js, src/game/builtin.js, src/game/challenges/asteroids_challenges.js, src/game/game.js, src/lesson/builtin.js, src/lesson/first_mission.js, src/lesson/lesson.js, src/util/resource_loader.js, src/util/translate.js, src/view/instruction_pane.js, src/view/lesson_environment.js, tests/lessons/lesson01.js
This introduces an architecture that is much more decoupled than what we
had before. It clearly separates what is a game, a challenge and a lesson.
In the near future, the notion of a "course" will also fit in naturally.
It is based on the following concepts:
- A Game is a set of rules in which challenges can be solved.
-- Games are played by a GameRunner (game/game.js).
- A challenge is a specific situation in which a specific game is played.
-- Challenges are represented by a Challenge (game/game.js)
- A Lesson is a sequence of challenges (lesson/lesson.js).
-- Lessons can contain challenges from multiple games (for example a
"review" lesson). Also, a challenge can be present in multiple
lessons (i.e. in an introductory lesson, and then again in a
"review" lesson).
Soon, a course will …
=> Major architecture design overhaul.

package.json, src/app.js, src/course/builtin.js, src/course/course.js, src/course/introduction.js, src/view/course_overview.js, src/view/lesson_environment.js, src/view/lesson_overview.js, tests/courses/introduction.html
Now, in order to view all lessons from the basic course, one can go to
/tests/courses/introduction.html instead of visiting individual lessons.
=> Implement Courses and a CourseOverview page.

src/app.js, src/backend/local_progress_manager.js, src/backend/progress_manager.js, src/game/game.js, src/lesson/lesson.js, src/view/course_overview.js, src/view/lesson_environment.js, src/view/lesson_overview.js, tests/courses/introduction.html
Also, add a simple, default in-memory implementation of a progress manager.
=> Add a pluggable progress management backend interface.

package.json, src/game/batteries.js, src/game/game.js, src/language/interpreter.js, src/language/robolang/lexer.js, src/language/robolang/parser.js, src/language/robolang/robolang.js, src/language/robolang/test/test_robolang.js, src/util/animator.js, src/view/code_editor.js, src/view/lesson_environment.js
This requires changes all over the code:
- The lexer + parser need to carry debugging information over tokens and
AST nodes, so that the interpreter can know what part of the code is
being executed
- The Animator now supports custom animation events, that cause a
callback to be called in certain points in the animation.
This is used to change the highlighted range of the code when
the current action changes.
- The LessonEnvironment uses such callback to change the highlighted
range.
- The events are produced by the game. Only the 'batteries' game was
altered in this PR. This part is simple, but needs to be implemented
on every game for now, since some games interact differently with the
interpreter (e.g. by setting variables during execution).
This can actually be generalized in the …
=> Highlight the code being executed.

package.json, src/constants.js, src/game/asteroids.js, src/game/batteries.js, src/language/robolang/lexer.js, src/language/robolang/parser.js, src/language/robolang/robolang.js, src/language/robolang/test/test_robolang.js, src/test/run_tests.js, src/view/code_editor.js, src/view/lesson_environment.js
This also implements substantial enhancements to the error system in
general. Messages are better formated and more informative, and all
errors are associated with a source code range in which they occur.
Fixes #46
=> Highlight code related to error messages.
